unstable_features = true
edition = "2018"
format_doc_comments = true
normalize_doc_attributes = true
normalize_comments = true
wrap_comments = true
tab_spaces = 2
reorder_imports = false
import_granularity = Crate
group_imports = StdExternalCrate