edition = "2018"
wrap_comments = true
tab_spaces = 2
reorder_imports = false
import_granularity = "Crate"
group_imports = "StdExternalCrate"

# unstable_features = true
# format_doc_comments = true
# normalize_doc_attributes = true
# normalize_comments = true
